kind: Service
apiVersion: v1
metadata:
  name:  server
spec:
  selector:
    app:  server
  ports:
  - name: express
    port:  3001
    targetPort:  3001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: nuwanudara/qserver:3.0.0
        resources:
          limits:
            memory: 316Mi
            cpu: 500m
        env:
        - name: MY_SQL_HOST
          value: "mysql-svc"
        - name: MY_SQL_USER
          value: "root"
        - name: MY_SQL_PASS
          value: "password"
        - name: MY_SQL_PORT
          value: "3306"
        - name: MY_SQL_DATABSE
          value: "myquo"