kind: Service
apiVersion: v1
metadata:
  name:  client
spec:
  selector:
    app:  client
  ports:
  - name: express
    port:  3000
    targetPort:  3000

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      containers:
      - name: client
        image: nuwanudara/qclient:2.0.0

        resources:
          limits:
            memory: 316Mi
            cpu: 500m

