apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: mysql-db
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      volumes:
        - name:  mysql-inits
          configMap:
            name:  mysql-init-config
        - name: my-db-pvc-storage
          persistentVolumeClaim:
            claimName: my-db-pvc 
      containers:
      - name: mysql
        image: mysql:latest
        volumeMounts:
        - name: mysql-inits
          mountPath: /docker-entrypoint-initdb.d
        - name: my-db-pvc-storage
          mountPath: /var/lib/mysql
        resources:
          limits:
            memory: 1024Mi
            cpu: 500m
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: "myquo"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mypass
              key: secretKey