apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-db-pv
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: ./db/
