apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-db-pvc
spec:
  accessModes:
  - ReadWriteMany
  volumeName: my-db-pv
  resources:
  requests:
    storage: 256Mi
  storageClassName: manual